import {notFound,redirect} from 'next/navigation';
import Link from 'next/link';
import {content,Locale,sections} from '../../../content';
import {SocialLinks} from '../../../components/SocialLinks';
import {getContactSettings} from '../../../lib/contact-service';
import {publicProjects} from '../../../lib/project-service';
import {ProjectCatalog} from '../../../components/ProjectCatalog';
import {AboutPage} from '../../../components/AboutPage';
import {Brief} from '../../../components/Brief';
import {ServicesPage} from '../../../components/ServicesPage';
const legal=['privacy','terms','storage'];
export function generateStaticParams(){return ['en','ar'].flatMap(locale=>[...sections,...legal,'projects'].map(section=>({locale,section})));}
export async function generateMetadata({params}:{params:Promise<{locale:string;section:string}>}){const {locale,section}=await params;if(locale!=='ar'&&locale!=='en')return {};const i=sections.indexOf(section as typeof sections[number]);return {title:i>=0?content[locale].nav[i+1]:({privacy:locale==='ar'?'سياسة الخصوصية':'Privacy policy',terms:locale==='ar'?'الشروط':'Terms',storage:locale==='ar'?'التخزين وملفات الارتباط':'Storage & cookies'} as Record<string,string>)[section]};}
export default async function Page({params}:{params:Promise<{locale:string;section:string}>}){
 const {locale,section}=await params;if(locale!=='ar'&&locale!=='en')notFound();if(section==='projects')redirect(`/${locale}/products`);
 if(![...sections,...legal].includes(section))notFound();const ar=locale==='ar',t=content[locale as Locale];
 if(legal.includes(section))return <div className="inner-page"><Legal section={section} ar={ar}/></div>;
 const contact=section==='contact'?await getContactSettings():null;
 const projects=section==='products'||section==='work'?await publicProjects(section==='products'?'product':'work'):[];
 const title=section==='about'?t.aboutPageTitle:section==='services'?(ar?'حلول تناسب طموحك.':'Services for your next chapter.'):section==='products'?(ar?'منتجات نبنيها بأنفسنا.':'Our ideas. Our products.'):section==='work'?(ar?'أعمالنا لعملائنا.':'Work for our clients.'):t.contactTitle;
 const desc=section==='about'?t.aboutText:section==='services'?(ar?'حلول في البرمجة والتسويق والذكاء الاصطناعي وتقنية المعلومات، مصممة حول احتياجات مشروعك.':'Technology, marketing, AI, and IT — everything your digital business needs under one roof.'):section==='products'?(ar?'حلول خاصة ب REDOM LABS للتجارة والخدمات اليومية.':'REDOM LABS products for commerce and everyday services.'):section==='work'?(ar?'مساحة مخصصة للمشاريع التي ننفذها للعملاء.':'A dedicated portfolio of projects delivered for clients.'):t.contactText;
 return <div className="inner-page"><section className="page-heading section"><p className="eyebrow">{t.nav[sections.indexOf(section as typeof sections[number])+1]}</p><h1>{title}</h1><p className="intro">{desc}</p></section>
 {section==='about'&&<AboutPage ar={ar}/>}
 {section==='services'&&<ServicesPage ar={ar} locale={locale} />}
 {(section==='products'||section==='work')&&<ProjectCatalog projects={projects} ar={ar}/>}
 {section==='contact'&&<section className="section contact-grid"><aside><h2>{t.contactSide}</h2><dl className="contact-details"><div><dt>{ar?'العنوان':'Location'}</dt><dd>{ar?contact?.address_ar:contact?.address_en}{(ar?contact?.address_details_ar:contact?.address_details_en)&&<p className="address-details">{ar?contact?.address_details_ar:contact?.address_details_en}</p>}</dd></div>{contact?.phone&&<div><dt>{ar?'الهاتف':'Phone'}</dt><dd><a dir="ltr" href={`tel:${contact.phone.replace(/[^+0-9]/g,'')}`}>{contact.phone}</a></dd></div>}{contact?.email&&<div><dt>{ar?'البريد الإلكتروني':'Email'}</dt><dd><a href={`mailto:${contact.email}`}>{contact.email}</a></dd></div>}</dl><SocialLinks links={contact?.social_links} ar={ar}/></aside><Brief ar={ar}/></section>}</div>;
}

function Legal({section,ar}:{section:string;ar:boolean}){
 const locale=ar?'ar':'en';const text:Record<string,string[][]>=ar?{
 privacy:[['سياسة الخصوصية','آخر تحديث: ٢ أكتوبر ٢٠٢٦'],['المحادثات','تُرسل رسائلك وسياق المحادثة إلى خادم الموقع، وقد تعالجها Vercel AI Gateway ومزوّد النموذج لتوليد الإجابة. لا تضف كلمات مرور أو بيانات حساسة. لا نخزّن المحادثات في قاعدة بيانات تطبيقنا؛ قد يحتفظ مزوّدو الخدمة بسجلات تشغيل وفق سياساتهم.'],['ملخص المشروع','عند إرسال النموذج نحفظ اسمك وبريدك ونوع المشروع ورسالتك في قاعدة بيانات Supabase للرد على استفسارك. يستطيع مسؤولو الشركة المصرح لهم الاطلاع عليها. المحادثة ليست قناة لإرسال مستندات أو طلبات رسمية.'],['الاستضافة والتفضيلات','قد تعالج الاستضافة بيانات تقنية مثل عنوان الشبكة ووقت الطلب للحماية والتشغيل. نحتفظ باختيار المظهر على جهازك. لا توجد أدوات تحليل أو تتبع إعلاني مضافة للموقع.'],['الاستفسارات والتحديثات','يمكنك سؤال المساعد عن استخدام الموقع. يمكنك إرسال طلب متعلق ببياناتك عبر نموذج التواصل. سنحدّث هذه الصفحة عند تغيير معالجة البيانات.']],
 terms:[['شروط الاستخدام','آخر تحديث: ٢ أكتوبر ٢٠٢٦'],['المعلومات والخدمات','المحتوى تعريفي وليس عرضًا تعاقديًا. نطاق الخدمة والتكلفة والجدول والالتزامات تُحدّد في اتفاق مستقل.'],['المساعد','المساعد يقدم إرشادات عن الموقع وقد يخطئ. لا يؤكد أسعارًا أو حجوزات أو تعاقدات، ولا ينفذ إجراءات نيابةً عنك.'],['الملكية والاستخدام','العلامة والمحتوى والمنتجات تخص أصحابها. لا تستخدم الموقع لإساءة الاستخدام أو تعطيل الخدمة أو الوصول غير المصرح به.'],['المنتجات والتحديثات','قد تكون للمنتجات شروط منفصلة. لا تُعرض روابط أو تفاصيل إتاحة قبل تأكيدها. قد يتغير المحتوى دون ضمان التوفر المستمر.']],
 storage:[['التخزين وملفات الارتباط','اختيارات بسيطة وواضحة.'],['تفضيل المظهر','يُحفظ اختيار المظهر في التخزين المحلي باسم indom-theme. يمكنك إزالته من إعدادات المتصفح؛ المظهر الافتراضي فاتح.'],['المحادثة','رسائل المحادثة محفوظة مؤقتًا في ذاكرة الصفحة ولا تُستعاد بعد إعادة تحميلها. إغلاق اللوحة لا يمسحها؛ زر مسح المحادثة يفعل ذلك.'],['التتبع','لوحة الإدارة تستخدم ملف ارتباط آمنًا للجلسة عند تسجيل دخول المسؤول، لمدة تصل إلى ساعة. لا نضيف ملفات ارتباط للإعلانات أو التحليلات. قد تستخدم الاستضافة آليات تقنية للحماية. يُرسل نموذج التواصل بياناتك عند الضغط على إرسال فقط.']]
 }:{
 privacy:[['Privacy policy','Updated October 2, 2026'],['Conversations','Your messages and conversation context are sent to our server and may be processed by Vercel AI Gateway and its model provider to generate a reply. Do not share passwords or sensitive information. We do not save chats in an application database; providers may retain operational logs under their policies.'],['Project briefs','Submitting the form stores your name, email, project type and message in Supabase so authorized company administrators can review and respond to your inquiry. Chat is not a channel for documents or formal requests.'],['Hosting & preferences','Hosting may process technical data such as IP addresses and request times for security and operation. Your theme preference is stored on your device. We have added no analytics or advertising trackers.'],['Questions & updates','You can ask the assistant about using the site. You can submit questions about your personal data through the contact form. We will update this page when data processing changes.']],
 terms:[['Terms of use','Updated October 2, 2026'],['Information & services','Site content is informational, not a contractual offer. Scope, price, timeline and obligations are set in a separate agreement.'],['Assistant','The assistant offers site guidance and can make mistakes. It cannot confirm pricing, bookings or contracts, or take actions on your behalf.'],['Ownership & use','Brands, content and products belong to their owners. Do not abuse the site, disrupt its services or attempt unauthorized access.'],['Products & updates','Products may have separate terms. Links and availability are published only when confirmed. Content can change and uninterrupted availability is not guaranteed.']],
 storage:[['Storage & cookies','Simple, transparent preferences.'],['Theme preference','Your theme choice is saved in local storage as indom-theme. Remove it through browser settings to reset the preference. The default theme is light.'],['Conversation','Chat messages live temporarily in page memory and are not restored after a reload. Closing the panel retains them; Clear conversation removes them.'],['Tracking','The admin area uses a secure session cookie for signed-in administrators, lasting up to one hour. We add no advertising or analytics cookies. Hosting may use technical security mechanisms. The contact form submits your details only when you choose Send message.']]
 };
 const [heading,...rows]=text[section];return <section className="section legal-page"><p className="eyebrow">REDOM LABS</p><h1>{heading[0]}</h1><p>{heading[1]}</p>{rows.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}<Link className="textlink" href={`/${locale}`}>{ar?'العودة للرئيسية':'Back to home'} ↗</Link></section>;
}
