import {notFound,redirect} from 'next/navigation';
import Link from 'next/link';
import {content,Locale,sections} from '../../../content';
import {Brief} from '../../../components/Brief';
import {ServicePaths} from '../../../components/ServicePaths';
const legal=['privacy','terms','storage'];
export function generateStaticParams(){return ['en','ar'].flatMap(locale=>[...sections,...legal,'projects'].map(section=>({locale,section})));}
export async function generateMetadata({params}:{params:Promise<{locale:string;section:string}>}){const {locale,section}=await params;if(locale!=='ar'&&locale!=='en')return {};const i=sections.indexOf(section as typeof sections[number]);return {title:i>=0?content[locale].nav[i+1]:({privacy:locale==='ar'?'سياسة الخصوصية':'Privacy policy',terms:locale==='ar'?'الشروط':'Terms',storage:locale==='ar'?'التخزين وملفات الارتباط':'Storage & cookies'} as Record<string,string>)[section]};}
export default async function Page({params}:{params:Promise<{locale:string;section:string}>}){
 const {locale,section}=await params;if(locale!=='ar'&&locale!=='en')notFound();if(section==='projects')redirect(`/${locale}/products`);
 if(![...sections,...legal].includes(section))notFound();const ar=locale==='ar',t=content[locale as Locale];
 if(legal.includes(section))return <Legal section={section} ar={ar}/>;
 const title=section==='about'?t.aboutPageTitle:section==='services'?t.servicesPageTitle:section==='products'?(ar?'منتجات نبنيها بأنفسنا.':'Our ideas. Our products.'):section==='work'?(ar?'أعمالنا لعملائنا.':'Work for our clients.'):t.contactTitle;
 const desc=section==='about'?t.aboutText:section==='services'?(ar?'تطوير تقني أو تسويق رقمي. اختر ما يحتاجه عملك.':'Technology or digital marketing. Choose what your business needs.'):section==='products'?(ar?'حلول خاصة بـ REDOM LABS للتجارة والخدمات اليومية.':'REDOM LABS products for commerce and everyday services.'):section==='work'?(ar?'مساحة مخصصة للمشاريع التي ننفذها للعملاء.':'A dedicated portfolio of projects delivered for clients.'):t.contactText;
 return <><section className="page-heading section"><p className="eyebrow">{t.nav[sections.indexOf(section as typeof sections[number])+1]}</p><h1>{title}</h1><p className="intro">{desc}</p></section>
 {section==='about'&&<><section className="section split"><h2>{t.founderTitle}</h2><p>{t.founderText}</p></section><section className="section"><p className="eyebrow">{t.valuesLabel}</p><div className="values">{t.values.map(([a,b])=><div key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></section></>}
 {section==='services'&&<section className="section services-detail"><ServicePaths ar={ar} detailed/></section>}
 {section==='products'&&<section className="section products-section"><div className="projects-grid">{['MenuzQR'].map((name,i)=><article key={name} className="project"><span className="eyebrow">{t.projectLabels[i]}</span><h2 dir="ltr">{name}</h2><p>{t.projectDescriptions[i]}</p><span className="project-index" aria-hidden>0{i+1}</span><details><summary>{ar?'عن المنتج':'About this product'}</summary><p>{ar?'منيو رقمي للمطاعم والكافيهات، مع إدارة الأقسام والمنتجات والأسعار.':'A digital menu for restaurants and cafés, with category, item and price management.'}</p></details></article>)}</div><p className="small collection-note">{ar?'المنتجات الخاصة بنا مستقلة عن أعمالنا لعملاء الشركة.':'Our own products are separate from our client portfolio.'}</p></section>}
 {section==='work'&&<section className="section"><div className="portfolio-empty"><p className="eyebrow">{ar?'أعمال العملاء':'Client portfolio'}</p><h2>{ar?'دراسات الحالة تُنشر هنا.':'Case studies belong here.'}</h2><p>{ar?'لا توجد دراسات حالة منشورة حاليًا. نشارك المشاريع عند توفر تفاصيلها واعتماد نشرها.':'No case studies are currently published. We share projects when their details and publication approval are available.'}</p><Link className="button" href={`/${locale}/services`}>{ar?'استكشف ما نقدمه':'Explore our services'} ↗</Link></div></section>}
 {section==='contact'&&<section className="section contact-grid"><aside><h2>{t.contactSide}</h2>{t.contactPoints.map(v=><p key={v}>↗ {v}</p>)}</aside><Brief ar={ar}/></section>}</>;
}
function Legal({section,ar}:{section:string;ar:boolean}){
 const locale=ar?'ar':'en';const text:Record<string,string[][]>=ar?{
 privacy:[['سياسة الخصوصية','آخر تحديث: ٢ أكتوبر ٢٠٢٦'],['المحادثات','تُرسل رسائلك وسياق المحادثة إلى خادم الموقع، وقد تعالجها Vercel AI Gateway ومزوّد النموذج لتوليد الإجابة. لا تضف كلمات مرور أو بيانات حساسة. لا نخزّن المحادثات في قاعدة بيانات تطبيقنا؛ قد يحتفظ مزوّدو الخدمة بسجلات تشغيل وفق سياساتهم.'],['ملخص المشروع','النموذج ينشئ ملفًا على جهازك فقط، ولا يرسل بياناتك إلى الشركة. المحادثة ليست قناة لإرسال مستندات أو طلبات رسمية.'],['الاستضافة والتفضيلات','قد تعالج الاستضافة بيانات تقنية مثل عنوان الشبكة ووقت الطلب للحماية والتشغيل. نحتفظ باختيار المظهر على جهازك. لا توجد أدوات تحليل أو تتبع إعلاني مضافة للموقع.'],['الاستفسارات والتحديثات','يمكنك سؤال المساعد عن استخدام الموقع. لم تُنشر قناة مخصصة لطلبات الخصوصية بعد؛ لا يعتبر نموذج الملخص إرسالًا لطلب. سنحدّث هذه الصفحة عند تغيير معالجة البيانات.']],
 terms:[['شروط الاستخدام','آخر تحديث: ٢ أكتوبر ٢٠٢٦'],['المعلومات والخدمات','المحتوى تعريفي وليس عرضًا تعاقديًا. نطاق الخدمة والتكلفة والجدول والالتزامات تُحدّد في اتفاق مستقل.'],['المساعد','المساعد يقدم إرشادات عن الموقع وقد يخطئ. لا يؤكد أسعارًا أو حجوزات أو تعاقدات، ولا ينفذ إجراءات نيابةً عنك.'],['الملكية والاستخدام','العلامة والمحتوى والمنتجات تخص أصحابها. لا تستخدم الموقع لإساءة الاستخدام أو تعطيل الخدمة أو الوصول غير المصرح به.'],['المنتجات والتحديثات','قد تكون للمنتجات شروط منفصلة. لا تُعرض روابط أو تفاصيل إتاحة قبل تأكيدها. قد يتغير المحتوى دون ضمان التوفر المستمر.']],
 storage:[['التخزين وملفات الارتباط','اختيارات بسيطة وواضحة.'],['تفضيل المظهر','يُحفظ اختيار المظهر في التخزين المحلي باسم indom-theme. يمكنك إزالته من إعدادات المتصفح؛ المظهر الافتراضي فاتح.'],['المحادثة','رسائل المحادثة محفوظة مؤقتًا في ذاكرة الصفحة ولا تُستعاد بعد إعادة تحميلها. إغلاق اللوحة لا يمسحها؛ زر مسح المحادثة يفعل ذلك.'],['التتبع','لوحة الإدارة تستخدم ملف ارتباط آمنًا للجلسة عند تسجيل دخول المسؤول، لمدة تصل إلى ساعة. لا نضيف ملفات ارتباط للإعلانات أو التحليلات. قد تستخدم الاستضافة آليات تقنية للحماية. لا يُنشأ ملف ملخص المشروع إلا عند اختيار تحميله.']]
 }:{
 privacy:[['Privacy policy','Updated October 2, 2026'],['Conversations','Your messages and conversation context are sent to our server and may be processed by Vercel AI Gateway and its model provider to generate a reply. Do not share passwords or sensitive information. We do not save chats in an application database; providers may retain operational logs under their policies.'],['Project briefs','The form creates a file on your device only. It does not send your details to the company. Chat is not a channel for documents or formal requests.'],['Hosting & preferences','Hosting may process technical data such as IP addresses and request times for security and operation. Your theme preference is stored on your device. We have added no analytics or advertising trackers.'],['Questions & updates','You can ask the assistant about using the site. A dedicated privacy request channel has not yet been published; downloading a brief does not submit a request. We will update this page when data processing changes.']],
 terms:[['Terms of use','Updated October 2, 2026'],['Information & services','Site content is informational, not a contractual offer. Scope, price, timeline and obligations are set in a separate agreement.'],['Assistant','The assistant offers site guidance and can make mistakes. It cannot confirm pricing, bookings or contracts, or take actions on your behalf.'],['Ownership & use','Brands, content and products belong to their owners. Do not abuse the site, disrupt its services or attempt unauthorized access.'],['Products & updates','Products may have separate terms. Links and availability are published only when confirmed. Content can change and uninterrupted availability is not guaranteed.']],
 storage:[['Storage & cookies','Simple, transparent preferences.'],['Theme preference','Your theme choice is saved in local storage as indom-theme. Remove it through browser settings to reset the preference. The default theme is light.'],['Conversation','Chat messages live temporarily in page memory and are not restored after a reload. Closing the panel retains them; Clear conversation removes them.'],['Tracking','The admin area uses a secure session cookie for signed-in administrators, lasting up to one hour. We add no advertising or analytics cookies. Hosting may use technical security mechanisms. A project brief file is created only when you choose to download it.']]
 };
 const [heading,...rows]=text[section];return <section className="section legal-page"><p className="eyebrow">REDOM LABS</p><h1>{heading[0]}</h1><p>{heading[1]}</p>{rows.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}<Link className="textlink" href={`/${locale}`}>{ar?'العودة للرئيسية':'Back to home'} ↗</Link></section>;
}
