'use client';
import {useEffect,useState,useRef} from 'react';
import {loadContactAdmin,saveContactSettings,deleteContactInquiry,loadOlderContactInquiries} from '../app/(admin)/admin/[locale]/contact-actions';
import {normalizeContact,socialPlatforms} from '../lib/contact-settings';
type Inquiry={id:string;name:string;email:string;project_type:string;message:string;created_at:string;locale:string};
export function AdminContact({ar,settings=false}:{ar:boolean;settings?:boolean}){
 const [data,setData]=useState<Awaited<ReturnType<typeof loadContactAdmin>>|null>(null),[notice,setNotice]=useState(''),[pending,setPending]=useState(false),[deleting,setDeleting]=useState<string|null>(null),[loadingMore,setLoadingMore]=useState(false),[hasMore,setHasMore]=useState(false);
 const cursor=useRef<Inquiry|null>(null);
 const text=(a:string,b:string)=>ar?a:b;
 useEffect(()=>{let active=true;loadContactAdmin().then(r=>{if(active){setData(r);setHasMore(r.inquiries.length===100);cursor.current=r.inquiries.at(-1)||null}});return ()=>{active=false}},[]);
 if(!data)return <p role="status">{text('جارٍ التحميل…','Loading…')}</p>;
 const values=normalizeContact(data.settings);
 const fields=[['address_en',text('المدينة والعنوان بالإنجليزية','Location in English')],['address_ar',text('المدينة والعنوان بالعربية','Location in Arabic')],['address_details_en',text('تفاصيل العنوان بالإنجليزية (اختياري)','Address details in English (optional)')],['address_details_ar',text('تفاصيل العنوان بالعربية (اختياري)','Address details in Arabic (optional)')],['phone',text('الهاتف (اختياري)','Phone (optional)')],['email',text('البريد الإلكتروني (اختياري)','Email (optional)')]] as const;
 async function remove(row:Inquiry){if(deleting||!confirm(text(`حذف رسالة ${row.name} نهائيًا؟ لا يمكن التراجع عن الحذف.`,`Permanently delete the inquiry from ${row.name}? This cannot be undone.`)))return;setDeleting(row.id);setNotice('');try{const ok=await deleteContactInquiry(row.id);if(ok)setData(current=>current?{...current,inquiries:current.inquiries.filter(item=>item.id!==row.id)}:current);setNotice(ok?text('تم حذف الرسالة.','Inquiry deleted.'):text('تعذر حذف الرسالة. تحقق من الصلاحيات وحاول مجددًا.','Unable to delete the inquiry. Check permissions and try again.'))}catch{setNotice(text('تعذر الاتصال. حاول مرة أخرى.','Unable to connect. Please try again.'))}finally{setDeleting(null)}}
 return <section className="admin-card"><h2>{settings?text('بيانات التواصل والسوشيال','Contact & social links'):text('رسائل التواصل','Contact inquiries')}</h2>{data.error&&<p role="alert">{text('تعذر الاتصال ببيانات التواصل. تحقق من إعداد جداول قاعدة البيانات.','Contact data is unavailable. Check the database table setup.')}</p>}{settings?<form className="brief" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setNotice('');try{const ok=await saveContactSettings(form);setNotice(ok?text('تم حفظ البيانات وروابط السوشيال.','Contact details and social links saved.'):text('تعذر الحفظ. تحقق من الروابط وملف SQL وحاول مرة أخرى.','Unable to save. Check URLs and the SQL setup, then try again.'))}catch{setNotice(text('تعذر الاتصال. حاول مرة أخرى.','Unable to connect. Please try again.'))}finally{setPending(false)}}}>
 <fieldset disabled={pending}><legend>{text('العنوان وطرق التواصل','Address & contact')}</legend>{fields.map(([key,label])=><label key={key}>{label}{key.startsWith('address_details')?<textarea name={key} defaultValue={values[key]} rows={3} maxLength={500} dir={key.endsWith('_ar')?'rtl':'ltr'}/>:<input name={key} type={key==='email'?'email':key==='phone'?'tel':'text'} defaultValue={values[key]} required={key==='address_en'||key==='address_ar'} maxLength={key==='phone'?40:key==='email'?254:200} dir={key==='address_ar'?'rtl':'ltr'}/>}</label>)}</fieldset>
 <fieldset disabled={pending}><legend>{text('صفحات السوشيال ميديا','Social media pages')}</legend><p className="admin-caption">{text('أضف الروابط الكاملة التي تبدأ بـ https://. اترك الحقل فارغًا لإخفاء الرابط من الموقع.','Add full https:// URLs. Leave a field blank to hide that link from the website.')}</p>{socialPlatforms.map(([key,label])=><label key={key}>{label}<input name={'social_'+key} type="url" placeholder="https://" pattern="https://.*" maxLength={2048} defaultValue={values.social_links[key]||''} dir="ltr"/></label>)}</fieldset><button className="button" disabled={pending}>{pending?text('جارٍ الحفظ…','Saving…'):text('حفظ بيانات التواصل','Save contact details')}</button></form>:<>{!data.error&&!data.inquiries.length&&<p>{text('لا توجد رسائل حتى الآن.','No inquiries yet.')}</p>}{(data.inquiries as Inquiry[]).map(row=><article key={row.id} className="contact-inquiry"><div className="inquiry-heading"><h3>{row.name}</h3><button type="button" className="admin-secondary admin-danger" disabled={!!deleting||loadingMore} onClick={()=>remove(row)} aria-label={text(`حذف رسالة ${row.name}`,`Delete inquiry from ${row.name}`)}>{deleting===row.id?text('جارٍ الحذف…','Deleting…'):text('حذف الرسالة','Delete inquiry')}</button></div><a href={`mailto:${row.email}`}>{row.email}</a><p><small>{row.project_type} · {new Date(row.created_at).toLocaleString(ar?'ar-EG':'en-GB')}</small></p><p style={{whiteSpace:'pre-wrap'}}>{row.message}</p></article>)}</>}{!settings&&hasMore&&<button type="button" className="admin-secondary" disabled={loadingMore||!!deleting} onClick={async()=>{const last=data.inquiries.at(-1)||cursor.current;if(!last)return;setLoadingMore(true);try{const page=await loadOlderContactInquiries(last.created_at,last.id);if(page.error)setNotice(text('تعذر تحميل الرسائل الأقدم. حاول مرة أخرى.','Unable to load older inquiries. Please try again.'));else{setData(current=>current?{...current,inquiries:[...current.inquiries,...page.data.filter(row=>!current.inquiries.some(existing=>existing.id===row.id))]}:current);setHasMore(page.data.length===100);cursor.current=page.data.at(-1)||last}}finally{setLoadingMore(false)}}}>{loadingMore?text('جارٍ التحميل…','Loading…'):text('تحميل الرسائل الأقدم','Load older inquiries')}</button>}<p role="status">{notice}</p></section>;
}
