'use client';
import {useEffect,useRef,useState} from 'react';
import {uploadProjectImage} from '../app/(admin)/admin/[locale]/project-actions';
import {cropGeometry,THUMBNAIL_WIDTH,THUMBNAIL_HEIGHT} from '../lib/image-crop';
type Props={ar:boolean;value?:string;multiple?:boolean;crop?:boolean;disabled?:boolean;maxFiles?:number;onImages:(urls:string[])=>void;onBusyChange?:(busy:boolean)=>void;upload?:(form:FormData)=>Promise<{url:string;error:boolean}>};
export function AdminImagePicker({ar,value='',multiple=false,crop=false,disabled=false,maxFiles=12,onImages,onBusyChange,upload=uploadProjectImage}:Props){
 const input=useRef<HTMLInputElement>(null),[dragging,setDragging]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[source,setSource]=useState('');const owned=useRef('');const locked=disabled||busy;
 const text=(a:string,b:string)=>ar?a:b;
 useEffect(()=>()=>{if(owned.current)URL.revokeObjectURL(owned.current)},[]);
 function closeCrop(){setSource('');if(owned.current){URL.revokeObjectURL(owned.current);owned.current=''}}
 async function send(files:File[]){setBusy(true);onBusyChange?.(true);setNotice('');const urls:string[]=[];let failed=false;try{for(const file of files){const form=new FormData();form.set('image',file);const result=await upload(form);if(result.error){failed=true;break}urls.push(result.url)}if(urls.length)onImages(urls);setNotice(failed?text('تعذر رفع بعض الصور. حاول مرة أخرى.','Some images could not be uploaded. Please try again.'):text('تم رفع الصور. احفظ التغييرات لتطبيقها.','Images uploaded. Save your changes to apply them.'));if(!failed)closeCrop();return !failed}catch{setNotice(text('تعذر الاتصال. حاول مرة أخرى.','Unable to connect. Please try again.'));return false}finally{setBusy(false);onBusyChange?.(false)}}
 function accept(files:File[]){if(locked)return;const selected=multiple?files:files.slice(0,1);if(!selected.length)return;if(selected.length>maxFiles){setNotice(text(`الحد الأقصى ${maxFiles} صورة إضافية.`,`You can add up to ${maxFiles} more images.`));return}if(selected.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5242880||f.size===0)){setNotice(text('استخدم PNG أو JPG أو WebP بحجم لا يتجاوز 5 MB للصورة.','Use PNG, JPG or WebP up to 5 MB per image.'));return}setNotice('');if(crop){if(owned.current)URL.revokeObjectURL(owned.current);owned.current=URL.createObjectURL(selected[0]);setSource(owned.current)}else void send(selected)}
 return <div className="image-picker"><div className={`image-dropzone ${dragging?'is-dragging':''}`} tabIndex={locked?-1:0} role="group" aria-label={text('رفع صورة بالسحب أو اللصق','Upload image by dropping or pasting')} aria-disabled={locked} onDragOver={e=>{e.preventDefault();if(!locked)setDragging(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);accept(Array.from(e.dataTransfer.files))}} onPaste={e=>{const files=Array.from(e.clipboardData.items).filter(i=>i.kind==='file').map(i=>i.getAsFile()).filter((f):f is File=>Boolean(f));if(files.length){e.preventDefault();accept(files)}}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&e.target===e.currentTarget){e.preventDefault();if(!locked)input.current?.click()}}}>
 <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 16v4h16v-4M12 16V4m-5 5 5-5 5 5"/></svg><strong>{busy?text('جارٍ رفع الصور…','Uploading images…'):text('اسحب صورة هنا أو الصقها','Drop an image here or paste it')}</strong><p>{text('اضغط داخل المربع ثم Ctrl + V، أو اختر صورة من جهازك.','Focus this area and press Ctrl + V, or choose a file.')}</p><button type="button" className="admin-secondary" disabled={locked} onClick={()=>input.current?.click()}>{text('اختيار الصور','Choose images')}</button><small>PNG · JPG · WebP · 5 MB</small><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" multiple={multiple} hidden disabled={locked} onChange={e=>{accept(Array.from(e.target.files||[]));e.target.value=''}}/>
 </div>{crop&&value&&<div className="image-picker-preview"><img src={value} alt={text('الصورة الرئيسية الحالية','Current thumbnail')} width={480} height={300}/><button type="button" className="admin-secondary" disabled={locked} onClick={()=>{setNotice('');setSource(value)}}>{text('ضبط إطار الصورة','Adjust image framing')}</button></div>}<p className="image-picker-notice" role="status">{notice}</p>
 {source&&<ThumbnailCrop ar={ar} source={source} busy={busy} onCancel={closeCrop} onSave={file=>send([file])}/>}
 </div>;
}
function ThumbnailCrop({ar,source,busy,onCancel,onSave}:{ar:boolean;source:string;busy:boolean;onCancel:()=>void;onSave:(file:File)=>Promise<boolean>}){
 const dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement|null>(null),pointer=useRef<{x:number;y:number;panX:number;panY:number}|null>(null);
 const [size,setSize]=useState({width:480,height:300}),[natural,setNatural]=useState({width:1,height:1}),[ready,setReady]=useState(false),[error,setError]=useState(''),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[rendering,setRendering]=useState(false);
 const text=(a:string,b:string)=>ar?a:b,locked=busy||rendering;
 useEffect(()=>{const element=dialog.current;element?.showModal();const node=stage.current;if(!node)return;const observer=new ResizeObserver(()=>setSize({width:node.clientWidth,height:node.clientHeight}));observer.observe(node);return ()=>{observer.disconnect();element?.close()}},[]);
 useEffect(()=>{let active=true;const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(active){image.current=img;setNatural({width:img.naturalWidth,height:img.naturalHeight});setReady(true)}};img.onerror=()=>{if(active)setError(text('تعذر تحميل الصورة للتعديل. ارفع نسخة من جهازك.','This image cannot be edited here. Upload a copy from your device.'))};img.src=source;return ()=>{active=false;image.current=null}},[source]);
 const geometry=cropGeometry(natural.width,natural.height,size.width,size.height,zoom,pan.x,pan.y);
 async function save(){if(!ready||!image.current||locked)return;setRendering(true);setError('');try{const canvas=document.createElement('canvas');canvas.width=THUMBNAIL_WIDTH;canvas.height=THUMBNAIL_HEIGHT;const context=canvas.getContext('2d');if(!context)throw Error();const g=cropGeometry(natural.width,natural.height,canvas.width,canvas.height,zoom,pan.x,pan.y);context.drawImage(image.current,g.left,g.top,g.imageWidth,g.imageHeight);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error()),'image/webp',.9));const type=blob.type==='image/webp'?'webp':'png';const uploaded=await onSave(new File([blob],`thumbnail.${type}`,{type:blob.type}));if(!uploaded)setError(text("تعذر رفع الصورة. حاول مرة أخرى.","Unable to upload the image. Please try again."))}catch{setError(text('تعذر تجهيز الصورة. ارفع نسخة من جهازك وحاول مجددًا.','Unable to prepare the image. Upload a local copy and try again.'))}finally{setRendering(false)}}
 return <dialog ref={dialog} className="admin-dialog thumbnail-dialog" onCancel={e=>{e.preventDefault();if(!locked)onCancel()}} aria-labelledby="thumbnail-crop-title"><div className="card-heading"><div><p className="eyebrow">{text('الصورة الرئيسية','Thumbnail')}</p><h2 id="thumbnail-crop-title">{text('اختَر الجزء اللي يظهر.','Choose what appears.')}</h2></div><button type="button" className="dialog-close" aria-label={text('إغلاق','Close')} disabled={locked} onClick={onCancel}>×</button></div><p>{text('اسحب الصورة داخل الإطار، واستخدم التكبير لضبط التكوين.','Drag the image inside the frame and adjust zoom to refine the composition.')}</p>
 <div ref={stage} className="thumbnail-crop-stage" dir="ltr" tabIndex={0} role="group" aria-label={text('إطار القص؛ استخدم الأسهم لتحريك الصورة','Crop frame; use arrow keys to move the image')} onPointerDown={e=>{if(!ready||locked)return;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={x:e.clientX,y:e.clientY,panX:pan.x,panY:pan.y}}} onPointerMove={e=>{if(!pointer.current||locked)return;const p=pointer.current;setPan({x:geometry.overflowX?Math.max(-1,Math.min(1,p.panX+(e.clientX-p.x)*2/geometry.overflowX)):0,y:geometry.overflowY?Math.max(-1,Math.min(1,p.panY+(e.clientY-p.y)*2/geometry.overflowY)):0})}} onPointerUp={()=>{pointer.current=null}} onPointerCancel={()=>{pointer.current=null}} onKeyDown={e=>{if(!ready||locked||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();setPan(p=>({x:Math.max(-1,Math.min(1,p.x+(e.key==='ArrowRight'?.05:e.key==='ArrowLeft'?-.05:0))),y:Math.max(-1,Math.min(1,p.y+(e.key==='ArrowDown'?.05:e.key==='ArrowUp'?-.05:0)))}))}}>{ready?<img src={source} alt="" draggable={false} style={{width:geometry.imageWidth,height:geometry.imageHeight,left:geometry.left,top:geometry.top}}/>:<span>{text('جارٍ تحميل الصورة…','Loading image…')}</span>}<div className="crop-grid" aria-hidden="true"/></div>
 <div className="crop-controls"><label>{text('التكبير','Zoom')}<input type="range" min={1} max={3} step={.01} value={zoom} disabled={!ready||locked} onChange={e=>setZoom(Number(e.target.value))}/><output>{Math.round(zoom*100)}%</output></label><button type="button" className="admin-secondary" disabled={locked} onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>{text('إعادة الضبط','Reset framing')}</button></div><small>{text('يتم حفظ نسخة بالمقاس 1200 × 750 للصورة الرئيسية.','Saves a 1200 × 750 thumbnail copy.')}</small>{error&&<p role="alert" className="login-error">{error}</p>}<div className="project-editor-actions"><button type="button" className="button" disabled={!ready||locked} onClick={save}>{locked?text('جارٍ الحفظ…','Saving…'):text('تطبيق الصورة','Apply image')}</button><button type="button" className="admin-secondary" disabled={locked} onClick={onCancel}>{text('إلغاء','Cancel')}</button></div></dialog>;
}
