'use client';
import {useEffect,useState} from 'react';
import {loadContactAdmin,saveContactSettings} from '../app/(admin)/admin/[locale]/contact-actions';
type Inquiry={id:string;name:string;email:string;project_type:string;message:string;created_at:string;locale:string};
export function AdminContact({ar,settings=false}:{ar:boolean;settings?:boolean}){
 const [data,setData]=useState<Awaited<ReturnType<typeof loadContactAdmin>>|null>(null),[notice,setNotice]=useState(''),[pending,setPending]=useState(false);
 useEffect(()=>{loadContactAdmin().then(setData)},[]);
 if(!data)return <p role="status">{ar?'جارٍ التحميل…':'Loading…'}</p>;
 const values=data.settings||{address_en:'Cairo - Egypt',address_ar:'القاهرة - مصر',phone:'',email:''};
 return <section className="admin-card"><h2>{settings?(ar?'بيانات التواصل':'Contact details'):(ar?'رسائل التواصل':'Contact inquiries')}</h2>{data.error&&<p role="alert">{ar?'تعذر الاتصال ببيانات التواصل. تحقق من إعداد جداول قاعدة البيانات.':'Contact data is unavailable. Check the database table setup.'}</p>}{settings?<form className="brief" onSubmit={async e=>{e.preventDefault();setPending(true);const ok=await saveContactSettings(new FormData(e.currentTarget));setNotice(ok?(ar?'تم حفظ البيانات.':'Contact details saved.'):(ar?'تعذر الحفظ. حاول مرة أخرى.':'Unable to save. Please try again.'));setPending(false)}}>{[['address_en',ar?'العنوان بالإنجليزية':'Address in English'],['address_ar',ar?'العنوان بالعربية':'Address in Arabic'],['phone',ar?'الهاتف':'Phone'],['email',ar?'البريد الإلكتروني':'Email']].map(([key,label])=><label key={key}>{label}<input name={key} type={key==='email'?'email':key==='phone'?'tel':'text'} defaultValue={values[key]} required={key.startsWith('address')} maxLength={key==='phone'?40:key==='email'?254:200} dir={key==='address_ar'?'rtl':'ltr'}/></label>)}<button className="button" disabled={pending}>{ar?'حفظ بيانات التواصل':'Save contact details'}</button><p role="status">{notice}</p></form>:<>{!data.error&&!data.inquiries.length&&<p>{ar?'لا توجد رسائل حتى الآن.':'No inquiries yet.'}</p>}{(data.inquiries as Inquiry[]).map(row=><article key={row.id} className="contact-inquiry"><h3>{row.name}</h3><a href={`mailto:${row.email}`}>{row.email}</a><p><small>{row.project_type} · {new Date(row.created_at).toLocaleString(ar?'ar-EG':'en-GB')}</small></p><p style={{whiteSpace:'pre-wrap'}}>{row.message}</p></article>)}</>}</section>;
}
