'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {logout} from '../app/(admin)/admin/[locale]/actions';
import {loadDashboardSummary} from '../app/(admin)/admin/[locale]/dashboard-actions';
import {AdminProjects} from './AdminProjects';
import {AdminContact} from './AdminContact';
import {AdminPasswordSettings} from './AdminPasswordSettings';
import {AdminProposalsManager} from './AdminProposalsManager';
type Tab='overview'|'products'|'work'|'proposals'|'inquiries'|'forms'|'settings';
const paths={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',products:'M4 7h16v14H4zM8 7V3h8v4M4 12h16',work:'M3 6h18v15H3zM8 6V3h8v3M3 11h18',proposals:'M6 3h9l4 4v14H6zM14 3v5h5M9 12h7M9 16h7',inquiries:'M3 5h18v14H3zM3 6l9 7 9-7',forms:'M5 3h14v18H5zM8 7h8M8 11h8M8 15h5',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6'};
function Icon({tab}:{tab:Tab}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[tab]}/></svg>}
export function AdminDashboard({ar}:{ar:boolean}){
 const locale=ar?'ar':'en',text=(a:string,b:string)=>ar?a:b;
 const [tab,setTab]=useState<Tab>('overview'),[mobile,setMobile]=useState(false),[summary,setSummary]=useState<Awaited<ReturnType<typeof loadDashboardSummary>>|null>(null);
 const items:Tab[]=['overview','products','work','proposals','inquiries','forms','settings'];
 const labels:Record<Tab,string>={overview:text('نظرة عامة','Overview'),products:text('المنتجات','Products'),work:text('أعمال العملاء','Client work'),proposals:text('العروض والمقترحات','Proposals'),inquiries:text('رسائل التواصل','Inquiries'),forms:text('نموذج التواصل','Contact form'),settings:text('الإعدادات','Settings')};
 const descriptions:Record<Tab,string>={overview:text('مساحة واحدة لإدارة المحتوى والتواصل مع العملاء.','One workspace for your content and customer conversations.'),products:text('منتجات Redom، من أول فكرة حتى النشر.','Manage Redom products from draft to publication.'),work:text('اعرض المشاريع المعتمدة وتفاصيل العمل لكل عميل.','Present approved projects and the work behind them.'),proposals:text('عروض خاصة بالعملاء وروابط محمية برمز مرور.','Client proposals with private, passcode-protected links.'),inquiries:text('راجع الرسائل الواردة وتواصل مع أصحابها.','Review incoming messages and contact their senders.'),forms:text('افتح النموذج المنشور على الموقع.','Open the contact form published on your website.'),settings:text('بيانات الشركة وإعدادات أمان الحساب.','Company contact details and account security.')};
 useEffect(()=>{function sync(){const value=new URL(window.location.href).searchParams.get('tab');setTab(value&&Object.hasOwn(paths,value)?value as Tab:'overview')}sync();window.addEventListener('popstate',sync);return ()=>window.removeEventListener('popstate',sync)},[]);
 useEffect(()=>{if(tab==='overview'){let active=true;loadDashboardSummary().then(r=>{if(active)setSummary(r)});return ()=>{active=false}}},[tab]);
 useEffect(()=>{if(!mobile)return;function esc(e:KeyboardEvent){if(e.key==='Escape')setMobile(false)}window.addEventListener('keydown',esc);return ()=>window.removeEventListener('keydown',esc)},[mobile]);
 function go(value:Tab){setTab(value);setMobile(false);const url=new URL(window.location.href);url.searchParams.set('tab',value);window.history.pushState({},'',url);}
 return <div className="admin-shell" dir={ar?'rtl':'ltr'} lang={locale}>{mobile&&<button className="admin-mobile-scrim" aria-label={text('إغلاق القائمة','Close navigation')} onClick={()=>setMobile(false)}/>}
 <aside className={`admin-sidebar ${mobile?'open':''}`} id="admin-navigation"><Link href={`/${locale}`} className="admin-wordmark">REDOM <span>LABS</span></Link><p className="workspace-label">{text('مساحة الإدارة','ADMIN WORKSPACE')}</p><nav aria-label={text('أقسام لوحة الإدارة','Administration sections')}>{items.map(item=><button key={item} onClick={()=>go(item)} aria-current={tab===item?'page':undefined}><Icon tab={item}/><span>{labels[item]}</span></button>)}</nav><div className="sidebar-bottom"><Link href={`/${locale}`} target="_blank" rel="noopener noreferrer">{text('عرض الموقع','View website')} <span aria-hidden="true">↗</span></Link><form action={logout}><input type="hidden" name="locale" value={locale}/><button>{text('تسجيل الخروج','Sign out')}</button></form></div></aside>
 <div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setMobile(v=>!v)} aria-expanded={mobile} aria-controls="admin-navigation" aria-label={text('قائمة الإدارة','Administration menu')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><p>{text('مساحة العمل','Workspace')} <span aria-hidden="true">/</span> <strong>{labels[tab]}</strong></p><div><Link className="admin-language" href={`/admin/${ar?'en':'ar'}/dashboard?tab=${tab}`}>{ar?'EN':'عربي'}</Link><span className="admin-avatar" aria-label={text('حساب المسؤول','Administrator account')}>R</span></div></header>
 <main className="admin-main"><div className="admin-title"><div><p className="eyebrow">REDOM LABS</p><h1>{labels[tab]}</h1><p className="admin-description">{descriptions[tab]}</p></div></div>
 {tab==='overview'&&<><div className="admin-stats">{(['products','work','proposals','inquiries'] as const).map(item=><button key={item} onClick={()=>go(item)}><div><span>{labels[item]}</span><Icon tab={item}/></div><strong>{!summary?'…':summary.error?'—':summary[item]}</strong><small>{text('عرض وإدارة','View and manage')} <span aria-hidden="true">↗</span></small></button>)}</div>{summary?.error&&<p className="admin-status" role="status">{text('تعذر تحميل الإحصاءات. تحقق من اتصال قاعدة البيانات.','Unable to load counts. Check your database connection.')}</p>}
 <div className="admin-overview-grid"><section className="admin-card admin-welcome"><p className="eyebrow">{text('خطوتك التالية','NEXT STEP')}</p><h2>{text('خلّي أعمالك تتكلم عنك.','Let your work speak for you.')}</h2><p>{text('أضف مشروعًا، رتّب صوره، واكتب التفاصيل التي تساعد الزائر يفهم قيمته.','Add a project, frame its images and write the details that help visitors understand its value.')}</p><div className="project-editor-actions"><button className="button" onClick={()=>go('work')}>{text('إدارة أعمال العملاء','Manage client work')}</button><button className="admin-secondary" onClick={()=>go('products')}>{text('إدارة المنتجات','Manage products')}</button></div></section><section className="admin-card"><div className="card-heading"><h2>{text('وصول سريع','Quick access')}</h2></div>{(['proposals','inquiries','settings'] as Tab[]).map(item=><button key={item} className="admin-shortcut" onClick={()=>go(item)}><span>{labels[item]}</span><span aria-hidden="true">↗</span></button>)}</section></div>
 <section className="admin-card admin-note"><div><h2>{text('حضور متناسق، وتفاصيل واضحة.','A consistent presence, with clear details.')}</h2><p>{text('المسودات لا تظهر للزوار. انشر المشروع عندما تكون الصور والوصف والرابط جاهزة.','Drafts stay private. Publish a project when its images, description and link are ready.')}</p></div><Link className="admin-secondary" href={`/${locale}/products`} target="_blank" rel="noopener noreferrer">{text('معاينة الموقع','Preview website')} ↗</Link></section></>}
 {tab==='products'&&<AdminProjects ar={ar} kind="product"/>}{tab==='work'&&<AdminProjects ar={ar} kind="work"/>}{tab==='proposals'&&<AdminProposalsManager ar={ar}/>}{tab==='inquiries'&&<AdminContact ar={ar}/>}
 {tab==='forms'&&<section className="admin-card admin-form-card"><h2>{text('نموذج واحد، وتواصل أبسط.','A simple way to start a conversation.')}</h2><p>{text('الرسائل الواردة تظهر في قسم رسائل التواصل. يمكنك تعديل عنوان الشركة ورقم الهاتف والبريد الإلكتروني من الإعدادات.','Submissions appear in Inquiries. Update your company address, phone number and email in Settings.')}</p><div className="project-editor-actions"><Link className="button" href={`/${locale}/contact`} target="_blank" rel="noopener noreferrer">{text('فتح نموذج التواصل','Open contact form')} ↗</Link><button className="admin-secondary" onClick={()=>go('settings')}>{text('تعديل بيانات التواصل','Edit contact details')}</button></div></section>}
 {tab==='settings'&&<div className="admin-settings-grid"><AdminContact ar={ar} settings/><AdminPasswordSettings ar={ar}/></div>}
 </main><footer className="admin-bottom"><span>REDOM LABS</span><span>{text('إدارة المحتوى والتواصل','Content & conversations')}</span></footer></div></div>;
}
