'use client';
import {useEffect,useState} from 'react';
import {emptyProject,type SiteProject,type ProjectKind} from '../lib/project-types';
import {loadProjects,saveProject,removeProject,uploadProjectImage} from '../app/(admin)/admin/[locale]/project-actions';
export function AdminProjects({ar,kind}:{ar:boolean;kind:ProjectKind}){
 const [projects,setProjects]=useState<SiteProject[]>([]),[editing,setEditing]=useState<SiteProject|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(false),[notice,setNotice]=useState(''),[search,setSearch]=useState('');
 async function reload(){setLoading(true);const r=await loadProjects(kind);setProjects(r.data);setError(r.error);setLoading(false)}
 useEffect(()=>{let active=true;setLoading(true);setEditing(null);loadProjects(kind).then(r=>{if(active){setProjects(r.data);setError(r.error);setLoading(false)}});return ()=>{active=false}},[kind]);
 const text=(a:string,b:string)=>ar?a:b;
 function update(key:keyof SiteProject,value:unknown){setEditing(p=>p?{...p,[key]:value}:null)}
 async function upload(files:FileList|null,gallery:boolean){if(!files||!editing)return;const selected=Array.from(files);if(gallery&&selected.length+editing.gallery_urls.length>12){setNotice(text('الحد الأقصى 12 صورة.','Maximum 12 gallery images.'));return}setBusy(true);const urls:string[]=[];let failed=false;try{for(const file of selected){const form=new FormData();form.set('image',file);const r=await uploadProjectImage(form);if(r.error){failed=true;break}urls.push(r.url)}setEditing(p=>p?{...p,...(gallery?{gallery_urls:[...p.gallery_urls,...urls]}:urls[0]?{thumbnail_url:urls[0]}:{})}:null);setNotice(failed?text('تعذر رفع بعض الصور. الحد 5 MB بصيغ PNG أو JPG أو WebP.','Some images could not be uploaded. Use PNG, JPG or WebP up to 5 MB.'):text('تم رفع الصور. احفظ المشروع لتثبيت التغييرات.','Images uploaded. Save the project to apply changes.'))}catch{setNotice(text('تعذر رفع الصور.','Unable to upload images.'))}finally{setBusy(false)}}
 return <section className="admin-card project-manager"><div className="card-heading"><h2>{kind==='product'?text('منتجاتنا','Our products'):text('أعمال العملاء','Client work')}</h2><button className="button" disabled={busy||error||loading} onClick={()=>{setNotice('');setEditing(emptyProject(kind))}}>{text('إضافة مشروع','Add project')} +</button></div><p>{text('المشاريع المنشورة تظهر على الموقع، والمسودات تظهر هنا فقط.','Published projects appear on the website. Drafts are visible here only.')}</p>{error&&<p role="alert">{text('تعذر تحميل المشاريع. شغّل ملف SQL لإعداد الجداول والصلاحيات.','Projects could not be loaded. Run the SQL setup for tables and permissions.')}</p>}{loading&&<p role="status">{text('جارٍ التحميل…','Loading…')}</p>}
 {!editing?<><label className="admin-search"><span className="sr-only">{text('بحث','Search')}</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={text('بحث عن مشروع…','Search projects…')}/></label><div className="admin-product-grid">{projects.filter(p=>(p.name_ar+p.name_en).toLowerCase().includes(search.toLowerCase())).map(p=><article className="admin-product" key={p.id}>{p.thumbnail_url&&<img className="admin-project-thumb" src={p.thumbnail_url} alt={ar?p.name_ar:p.name_en}/>}<span className="admin-tag">{p.published?text('منشور','Published'):text('مسودة','Draft')}</span><h3>{ar?p.name_ar:p.name_en}</h3><p>{ar?p.summary_ar:p.summary_en}</p><button className="admin-secondary" onClick={()=>{setNotice('');setEditing(p)}}>{text('تعديل التفاصيل','Edit details')}</button></article>)}</div>{!loading&&!error&&!projects.length&&<p>{text('أضف أول مشروع لعرضه هنا.','Add your first project to get started.')}</p>}</>:<form onSubmit={async e=>{e.preventDefault();if(!editing)return;setBusy(true);const ok=await saveProject(editing);setNotice(ok?text('تم حفظ المشروع.','Project saved.'):text('تعذر الحفظ. تحقق من الحقول وإعداد قاعدة البيانات.','Unable to save. Check the fields and database setup.'));if(ok){setEditing(null);await reload()}setBusy(false)}}>
 <div className="project-editor-grid">{(['name_ar','name_en','category_ar','category_en','summary_ar','summary_en','description_ar','description_en','client_name','year','slug','website_url'] as const).map((key,i)=>{const labels=ar?['الاسم بالعربية','الاسم بالإنجليزية','التصنيف بالعربية','التصنيف بالإنجليزية','وصف مختصر بالعربية','وصف مختصر بالإنجليزية','تفاصيل بالعربية','تفاصيل بالإنجليزية','اسم العميل (اختياري)','السنة','معرّف الرابط (حروف إنجليزية)','رابط الموقع (اختياري)']:['Arabic name','English name','Arabic category','English category','Arabic summary','English summary','Arabic details','English details','Client name (optional)','Year','Slug (English letters)','Website URL (optional)'];const multiline=key.startsWith('description')||key.startsWith('summary');return <label key={key}>{labels[i]}{multiline?<textarea value={editing[key]} onChange={e=>update(key,e.target.value)} dir={key.endsWith('_ar')?'rtl':'ltr'} rows={key.startsWith('description')?5:2} maxLength={key.startsWith('description')?6000:500} required={key.startsWith('summary')}/>:<input value={editing[key]} onChange={e=>update(key,e.target.value)} dir={key.endsWith('_ar')?'rtl':'ltr'} type={key==='website_url'?'url':'text'} required={key.startsWith('name')||key==='slug'} maxLength={key==='slug'?80:1000}/>}</label>})}
 {(['features_ar','features_en'] as const).map(key=><label key={key}>{key==='features_ar'?text('المميزات بالعربية (سطر لكل ميزة)','Arabic features (one per line)'):text('المميزات بالإنجليزية (سطر لكل ميزة)','English features (one per line)')}<textarea rows={4} dir={key.endsWith('_ar')?'rtl':'ltr'} value={editing[key].join('\n')} onChange={e=>update(key,e.target.value.split('\n'))}/></label>)}
 <label>{text('ترتيب العرض','Display order')}<input type="number" min={0} max={9999} value={editing.sort_order} onChange={e=>update('sort_order',Number(e.target.value))}/></label><label>{text('حالة النشر','Publication')}<select value={editing.published?'published':'draft'} onChange={e=>update('published',e.target.value==='published')}><option value="draft">{text('مسودة','Draft')}</option><option value="published">{text('منشور','Published')}</option></select></label></div>
 <fieldset><legend>{text('الصورة الرئيسية','Thumbnail')}</legend><label>{text('رفع صورة','Upload image')}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files,false)}/></label><label>{text('أو رابط الصورة','Or image URL')}<input type="url" value={editing.thumbnail_url} onChange={e=>update('thumbnail_url',e.target.value)}/></label>{editing.thumbnail_url&&<div className="admin-image-item"><img src={editing.thumbnail_url} alt={text('الصورة الرئيسية','Thumbnail')}/><button type="button" className="admin-secondary" onClick={()=>update('thumbnail_url','')}>{text('إزالة من المشروع','Remove from project')}</button></div>}</fieldset>
 <fieldset><legend>{text('معرض الصور','Image gallery')}</legend><label>{text('إضافة صور (حتى 12 صورة)','Add images (up to 12)')}<input type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files,true)}/></label><div className="admin-image-grid">{editing.gallery_urls.map((url,i)=><div key={i} className="admin-image-item"><img src={url} alt={`${text('صورة','Image')} ${i+1}`}/><button type="button" className="admin-secondary" onClick={()=>update('gallery_urls',editing.gallery_urls.filter((_,index)=>index!==i))}>{text('إزالة','Remove')}</button></div>)}</div></fieldset>
 <div className="project-editor-actions"><button className="button" disabled={busy}>{busy?text('جارٍ الحفظ…','Saving…'):text('حفظ المشروع','Save project')}</button><button className="admin-secondary" type="button" disabled={busy} onClick={()=>setEditing(null)}>{text('إلغاء','Cancel')}</button>{projects.some(p=>p.id===editing.id)&&<button className="admin-secondary" type="button" disabled={busy} onClick={async()=>{if(!confirm(text('حذف المشروع من قاعدة البيانات والموقع؟','Delete this project from the database and website?')))return;setBusy(true);const ok=await removeProject(editing.id);if(ok){setEditing(null);await reload()}setNotice(ok?text('تم حذف المشروع.','Project deleted.'):text('تعذر حذف المشروع.','Unable to delete project.'));setBusy(false)}}>{text('حذف المشروع','Delete project')}</button>}</div>
 </form>}<p role="status">{notice}</p></section>
}
