'use server';
import {contactAdminClient} from '../../../../lib/contact-service';
import {safeImageUrl,safeWebUrl,type ProjectKind,type SiteProject} from '../../../../lib/project-types';
import {revalidatePath} from 'next/cache';
export async function loadProjects(kind:ProjectKind){try{if(!['product','work'].includes(kind))throw Error();const client=await contactAdminClient();const {data,error}=await client.from('site_projects').select('*').eq('kind',kind).order('sort_order').order('created_at');if(error)throw error;return {data:data as SiteProject[],error:false}}catch{return {data:[] as SiteProject[],error:true}}}
export async function saveProject(project:SiteProject){try{
 if(!project||!['product','work'].includes(project.kind)||!/^[0-9a-f-]{36}$/i.test(project.id)||! /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(project.slug)||project.slug.length>80)return false;
 const fields=['name_ar','name_en','category_ar','category_en','summary_ar','summary_en','description_ar','description_en','client_name','year','website_url','thumbnail_url'] as const;
 for(const key of fields)if(typeof project[key]!=='string'||project[key].length>(key.startsWith('description')?6000:key.startsWith('summary')?500:1000))return false;
 if(!project.name_ar.trim()||!project.name_en.trim()||!project.summary_ar.trim()||!project.summary_en.trim()||!safeWebUrl(project.website_url)||!safeImageUrl(project.thumbnail_url))return false;
 if(!Array.isArray(project.gallery_urls)||project.gallery_urls.length>12||project.gallery_urls.some(v=>typeof v!=='string'||v.length>1000||!safeImageUrl(v)))return false;
 for(const key of ['features_ar','features_en'] as const)if(!Array.isArray(project[key])||project[key].length>20||project[key].some(v=>typeof v!=='string'||v.length>300))return false;
 if(typeof project.published!=='boolean'||!Number.isInteger(project.sort_order)||project.sort_order<0||project.sort_order>9999)return false;
 const client=await contactAdminClient();const payload={id:project.id,kind:project.kind,slug:project.slug,published:project.published,sort_order:project.sort_order,gallery_urls:project.gallery_urls,features_ar:project.features_ar.map(v=>v.trim()).filter(Boolean),features_en:project.features_en.map(v=>v.trim()).filter(Boolean),...Object.fromEntries(fields.map(key=>[key,project[key].trim()]))};
 const {error}=await client.from('site_projects').upsert(payload);if(error)return false;for(const locale of ['ar','en']){revalidatePath(`/${locale}/products`);revalidatePath(`/${locale}/work`)}return true;
 }catch{return false}}
export async function removeProject(id:string){try{if(!/^[0-9a-f-]{36}$/i.test(id))return false;const client=await contactAdminClient();const {error}=await client.from('site_projects').delete().eq('id',id);if(error)return false;for(const l of ['ar','en'])for(const s of ['products','work'])revalidatePath(`/${l}/${s}`);return true}catch{return false}}
export async function uploadProjectImage(form:FormData){try{const client=await contactAdminClient(),file=form.get('image');if(!(file instanceof File)||file.size===0||file.size>5*1024*1024)return {url:'',error:true};const buffer=Buffer.from(await file.arrayBuffer());let ext='';if(buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ext='png';else if(buffer[0]===255&&buffer[1]===216&&buffer[2]===255)ext='jpg';else if(buffer.toString('ascii',0,4)==='RIFF'&&buffer.toString('ascii',8,12)==='WEBP')ext='webp';if(!ext)return {url:'',error:true};const path=`projects/${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('site-images').upload(path,buffer,{contentType:ext==='jpg'?'image/jpeg':`image/${ext}`,cacheControl:'31536000',upsert:false});if(error)throw error;return {url:client.storage.from('site-images').getPublicUrl(path).data.publicUrl,error:false}}catch{return {url:'',error:true}}}
