export type Locale = 'en' | 'ar';
export const sections = ['about', 'services', 'products', 'work', 'contact'] as const;
export const content = {
  en: {
    nav: ['Home', 'About', 'Services', 'Products', 'Work', 'Contact'], start: 'Start your project', skip: 'Skip to content',
    studio: 'Technology & marketing', headline: ['Your next idea.', 'Our next creation.'],
    intro: 'Software, design and marketing. Built around your business.', slogan: 'From Innovation to Domination',
    explore: 'Explore services', capability: 'Our expertise', allServices: 'All services',
    serviceTitle: 'What can we build for you?', serviceIntro: 'Clear solutions for your next move.',
    services: [
      ['01', 'Websites & SaaS', 'Websites, landing pages and platforms.'],
      ['02', 'Mobile & desktop apps', 'Applications for your customers and team.'],
      ['03', 'AI & automation', 'Intelligent tools. Simpler workflows.'],
      ['04', 'Design & branding', 'Distinctive brands and intuitive interfaces.'],
      ['05', 'Digital marketing', 'Social media, content and performance campaigns.'],
      ['06', 'Product strategy', 'Feasibility, scope and a clear roadmap.'],
    ],
    aboutLabel: 'About Redom', aboutTitle: 'Ideas into useful experiences.',
    aboutText: 'Redom Labs brings software, design and marketing together to build practical digital solutions for businesses.', aboutLink: 'Meet Redom',
    processLabel: 'Our approach', processTitle: 'From idea to launch.', processIntro: 'A clear scope. Direct communication. Thoughtful execution.',
    steps: [['Discover', 'Understand your goals.'], ['Define', 'Set the scope and priorities.'], ['Build', 'Design, develop and refine.'], ['Launch', 'Release, learn and improve.']],
    valuesLabel: 'Our principles', values: [['Purpose', 'Solve a real business need.'], ['Care', 'Make every interaction clear.'], ['Clarity', 'Keep you involved at every step.']],
    cta: 'Let’s build what’s next.', ctaText: 'A good project starts with a clear conversation.', footer: 'Technology. Design. Growth.', rights: 'Redom Labs. All rights reserved.',
    aboutPageTitle: 'Technology meets ambition.', founderLabel: 'How we work', founderTitle: 'Built with purpose.',
    founderText: 'We connect strategy, design and engineering to deliver useful digital experiences.',
    futureTitle: 'Room to explore.', futureText: 'Software and marketing are our focus. Hardware remains a future ambition.',
    servicesPageTitle: 'Expertise for your next move.', servicePageIntro: 'One service or a complete digital solution. Shaped around your goals.',
    projectsTitle: 'Our own ideas, in motion.', projectsIntro: 'Products exploring everyday needs in commerce and local services.',
    projectLabels: ['Hospitality'],
    projectDescriptions: ['Digital menus and restaurant tools.'],
    contactTitle: 'Tell us what you have in mind.', contactText: 'Prepare a short brief to start the conversation.', contactSide: 'Start with the essentials.',
    contactPoints: ['The problem you want to solve.', 'The people you want to reach.', 'Your priorities for the first release.'],
  },
  ar: {
    nav: ['الرئيسية', 'عن الشركة', 'خدماتنا', 'منتجاتنا', 'أعمالنا', 'تواصل معنا'], start: 'ابدأ مشروعك', skip: 'انتقل للمحتوى',
    studio: 'تكنولوجيا وتسويق', headline: ['أفكار طموحة.', 'حلول تصنع الفرق.'],
    intro: 'نطوّر منتجاتك الرقمية ونبني حضور علامتك.', slogan: 'من الابتكار إلى الريادة',
    explore: 'اكتشف خدماتنا', capability: 'خدماتنا', allServices: 'كل الخدمات',
    serviceTitle: 'اختر مسار نموّك.', serviceIntro: 'حلول واضحة لخطوتك الجاية.',
    services: [
      ['٠١', 'مواقع ومنصات SaaS', 'مواقع وصفحات هبوط ومنصات متكاملة.'],
      ['٠٢', 'تطبيقات موبايل وديسكتوب', 'تطبيقات لعملائك وفريق شغلك.'],
      ['٠٣', 'ذكاء اصطناعي وأتمتة', 'أدوات أذكى وخطوات شغل أبسط.'],
      ['٠٤', 'تصميم وهوية بصرية', 'علامة مميزة وتجربة استخدام واضحة.'],
      ['٠٥', 'تسويق رقمي', 'إدارة سوشيال ميديا ومحتوى وحملات إعلانية.'],
      ['٠٦', 'استراتيجية المنتجات', 'جدوى وأولويات وخطة تنفيذ واضحة.'],
    ],
    aboutLabel: 'عن Redom', aboutTitle: 'من الفكرة لتجربة مفيدة.',
    aboutText: 'Redom Labs تجمع البرمجة والتصميم والتسويق لبناء حلول رقمية عملية للأعمال.', aboutLink: 'اعرفنا أكتر',
    processLabel: 'طريقة شغلنا', processTitle: 'من الفكرة للإطلاق.', processIntro: 'خطة واضحة. تواصل مباشر. تنفيذ مدروس.',
    steps: [['نفهم', 'نحدد أهداف مشروعك.'], ['نخطط', 'نتفق على النطاق والأولويات.'], ['نطوّر', 'نصمم ونبني ونحسن.'], ['نطلق', 'نبدأ ونتعلم ونكمل التطوير.']],
    valuesLabel: 'مبادئنا', values: [['هدف واضح', 'نحل احتياج حقيقي لشغلك.'], ['اهتمام بالتفاصيل', 'كل خطوة سهلة وواضحة.'], ['شفافية', 'أنت جزء من كل مرحلة.']],
    cta: 'جاهز لخطوتك الجاية؟', ctaText: 'خلّينا نبدأ بفكرتك.', footer: 'تكنولوجيا. تصميم. نمو.', rights: 'Redom Labs. جميع الحقوق محفوظة.',
    aboutPageTitle: 'تكنولوجيا بطموح أكبر.', founderLabel: 'نهجنا', founderTitle: 'حلول تبدأ بهدف واضح.',
    founderText: 'نجمع الاستراتيجية والتصميم والتطوير لبناء تجارب رقمية تخدم أهداف الأعمال.',
    futureTitle: 'مساحة لأفكار جديدة.', futureText: 'تركيزنا على البرمجيات والتسويق، والهاردوير جزء من طموحنا للمستقبل.',
    servicesPageTitle: 'خبرة لخطوتك الجاية.', servicePageIntro: 'خدمة محددة أو حل رقمي متكامل، حسب أهداف مشروعك.',
    projectsTitle: 'أفكارنا بتاخد شكل.', projectsIntro: 'منتجات بتستكشف احتياجات يومية في التجارة والخدمات.',
    projectLabels: ['المطاعم والكافيهات'],
    projectDescriptions: ['منيو رقمي وأدوات للمطاعم والكافيهات.'],
    contactTitle: 'احكي لنا عن فكرتك.', contactText: 'جهّز ملخص بسيط كبداية للتواصل.', contactSide: 'ابدأ بالتفاصيل الأساسية.',
    contactPoints: ['المشكلة اللي محتاج تحلها.', 'الجمهور اللي عايز توصله.', 'أولويات أول نسخة من مشروعك.'],
  },
};
